/**
 * dofusdude
 * # Open Ankama Developer Community The all-in-one toolbelt for your next Ankama related project.  ## Versions - [Dofus 2](https://docs.dofusdu.de/dofus2/) - [Dofus 3](https://docs.dofusdu.de/dofus3/)   - v1 [latest] (you are here)   ## Client SDKs - [Javascript](https://github.com/dofusdude/dofusdude-js) `npm i dofusdude-js --save` - [Typescript](https://github.com/dofusdude/dofusdude-ts) `npm i dofusdude-ts --save` - [Go](https://github.com/dofusdude/dodugo) `go get -u github.com/dofusdude/dodugo` - [Python](https://github.com/dofusdude/dofusdude-py) `pip install dofusdude` - [Java](https://github.com/dofusdude/dofusdude-java) Maven with GitHub packages setup  Everything, including this site, is generated out of the [Docs Repo](https://github.com/dofusdude/api-docs). Consider it the Single Source of Truth. If there is a problem with the SDKs, create an issue there.  Your favorite language is missing? Please let me know!  # Main Features - 🥷 **Seamless Auto-Update** load data in the background when a new Dofus version is released and serving it within 10 minutes with atomic data source switching. No downtime and no effects for the user, just always up-to-date.  - ⚡ **Blazingly Fast** all data in-memory, aggressive caching over short time spans, HTTP/2 multiplexing, written in Go, optimized for low latency, hosted on bare metal in 🇩🇪.  - 📨 **Almanax Discord Integration** Use the endpoints as a dev or the official [Web Client](https://discord.dofusdude.com) as a user.  - 🩸 **Dofus 3 Beta** from stable to bleeding edge by replacing /dofus3 with /dofus3beta.  - 🗣️ **Multilingual** supporting _en_, _fr_, _es_, _pt_, _de_.  - 🧠 **Search by Relevance** allowing typos in name and description, handled by language specific text analysis and indexing.  - 🕵️ **Official Sources** generated from actual data from the game.  ... and much more on the Roadmap on my [Discord](https://discord.gg/3EtHskZD8h). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: stelzo@steado.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AlmanaxBonus from './AlmanaxBonus';
import AlmanaxTribute from './AlmanaxTribute';

/**
 * The Almanax model module.
 * @module model/Almanax
 * @version 1.0.0
 */
class Almanax {
    /**
     * Constructs a new <code>Almanax</code>.
     * @alias module:model/Almanax
     */
    constructor() { 
        
        Almanax.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Almanax</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Almanax} obj Optional instance to populate.
     * @return {module:model/Almanax} The populated <code>Almanax</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Almanax();

            if (data.hasOwnProperty('bonus')) {
                obj['bonus'] = AlmanaxBonus.constructFromObject(data['bonus']);
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('tribute')) {
                obj['tribute'] = AlmanaxTribute.constructFromObject(data['tribute']);
            }
            if (data.hasOwnProperty('reward_kamas')) {
                obj['reward_kamas'] = ApiClient.convertToType(data['reward_kamas'], 'Number');
            }
            if (data.hasOwnProperty('reward_xp')) {
                obj['reward_xp'] = ApiClient.convertToType(data['reward_xp'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Almanax</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Almanax</code>.
     */
    static validateJSON(data) {
        // validate the optional field `bonus`
        if (data['bonus']) { // data not null
          AlmanaxBonus.validateJSON(data['bonus']);
        }
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }
        // validate the optional field `tribute`
        if (data['tribute']) { // data not null
          AlmanaxTribute.validateJSON(data['tribute']);
        }

        return true;
    }


}



/**
 * @member {module:model/AlmanaxBonus} bonus
 */
Almanax.prototype['bonus'] = undefined;

/**
 * @member {String} date
 */
Almanax.prototype['date'] = undefined;

/**
 * @member {module:model/AlmanaxTribute} tribute
 */
Almanax.prototype['tribute'] = undefined;

/**
 * Amount of Kamas you get as reward for finishing this Almanax quest.
 * @member {Number} reward_kamas
 */
Almanax.prototype['reward_kamas'] = undefined;

/**
 * Optional field that shows when a level is given in the request. Shows the experience points you get this day for finishing this Almanax quest.
 * @member {Number} reward_xp
 */
Almanax.prototype['reward_xp'] = undefined;






export default Almanax;

