/**
 * dofusdude
 * # Open Ankama Developer Community The all-in-one toolbelt for your next Ankama related project.  ## Versions - [Dofus 2](https://docs.dofusdu.de/dofus2/) - [Dofus 3](https://docs.dofusdu.de/dofus3/)   - v1 [latest] (you are here)   ## Client SDKs - [Javascript](https://github.com/dofusdude/dofusdude-js) `npm i dofusdude-js --save` - [Typescript](https://github.com/dofusdude/dofusdude-ts) `npm i dofusdude-ts --save` - [Go](https://github.com/dofusdude/dodugo) `go get -u github.com/dofusdude/dodugo` - [Python](https://github.com/dofusdude/dofusdude-py) `pip install dofusdude` - [Java](https://github.com/dofusdude/dofusdude-java) Maven with GitHub packages setup  Everything, including this site, is generated out of the [Docs Repo](https://github.com/dofusdude/api-docs). Consider it the Single Source of Truth. If there is a problem with the SDKs, create an issue there.  Your favorite language is missing? Please let me know!  # Main Features - 🥷 **Seamless Auto-Update** load data in the background when a new Dofus version is released and serving it within 10 minutes with atomic data source switching. No downtime and no effects for the user, just always up-to-date.  - ⚡ **Blazingly Fast** all data in-memory, aggressive caching over short time spans, HTTP/2 multiplexing, written in Go, optimized for low latency, hosted on bare metal in 🇩🇪.  - 📨 **Almanax Discord Integration** Use the endpoints as a dev or the official [Web Client](https://discord.dofusdude.com) as a user.  - 🩸 **Dofus 3 Beta** from stable to bleeding edge by replacing /dofus3 with /dofus3beta.  - 🗣️ **Multilingual** supporting _en_, _fr_, _es_, _pt_, _de_.  - 🧠 **Search by Relevance** allowing typos in name and description, handled by language specific text analysis and indexing.  - 🕵️ **Official Sources** generated from actual data from the game.  ... and much more on the Roadmap on my [Discord](https://discord.gg/3EtHskZD8h). 
 *
 * The version of the OpenAPI document: 1.0.0-rc.5
 * Contact: stelzo@steado.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateAlmanaxWebhookMentionsValueInner model module.
 * @module model/CreateAlmanaxWebhookMentionsValueInner
 * @version 1.0.0-rc.5
 */
class CreateAlmanaxWebhookMentionsValueInner {
    /**
     * Constructs a new <code>CreateAlmanaxWebhookMentionsValueInner</code>.
     * Mention
     * @alias module:model/CreateAlmanaxWebhookMentionsValueInner
     */
    constructor() { 
        
        CreateAlmanaxWebhookMentionsValueInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateAlmanaxWebhookMentionsValueInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateAlmanaxWebhookMentionsValueInner} obj Optional instance to populate.
     * @return {module:model/CreateAlmanaxWebhookMentionsValueInner} The populated <code>CreateAlmanaxWebhookMentionsValueInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateAlmanaxWebhookMentionsValueInner();

            if (data.hasOwnProperty('discord_id')) {
                obj['discord_id'] = ApiClient.convertToType(data['discord_id'], 'Number');
            }
            if (data.hasOwnProperty('is_role')) {
                obj['is_role'] = ApiClient.convertToType(data['is_role'], 'Boolean');
            }
            if (data.hasOwnProperty('ping_days_before')) {
                obj['ping_days_before'] = ApiClient.convertToType(data['ping_days_before'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateAlmanaxWebhookMentionsValueInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateAlmanaxWebhookMentionsValueInner</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * User or role ID directly from Discord. Activate developer mode and right click a user or role to get them.
 * @member {Number} discord_id
 */
CreateAlmanaxWebhookMentionsValueInner.prototype['discord_id'] = undefined;

/**
 * Whether an ID describes a role (true) or user (false). This is needed for formatting the mention command so Discord understands it.
 * @member {Boolean} is_role
 */
CreateAlmanaxWebhookMentionsValueInner.prototype['is_role'] = undefined;

/**
 * Get a mention days before the bonus comes up. It will post on the specified time. Also works when the interval is not daily.
 * @member {Number} ping_days_before
 */
CreateAlmanaxWebhookMentionsValueInner.prototype['ping_days_before'] = undefined;






export default CreateAlmanaxWebhookMentionsValueInner;

